# process names are case-insensitive
# you can use 'master' to indicate the master channel, or a list of process names to create a group
# you can use 'mic' to control your mic input level (uses the default recording device)
# you can use 'deej.unmapped' to control all apps that aren't bound to any slider (this ignores master, system, mic and device-targeting sessions)
# windows only - you can use 'deej.current' to control the currently active app (whether full-screen or not)
# windows only - you can use a device's full name, i.e. "Speakers (Realtek High Definition Audio)", to bind it. this works for both output and input devices
# windows only - you can use 'system' to control the "system sounds" volume
# important: slider indexes start at 0, regardless of which analog pins you're using!
slider_mapping:
  0: master                   # master mapping
  1: chrome.exe               # Chrome
  2: BH3.exe                  # Honkai Impact 3rd
  3: GenshinImpact.exe        # Genshin Impact
  4: StarRail.exe             # Star Rail
  # 5: discord.exe              # discord
  # 6: Valorant.exe             # Valorant
  # 7: mic Realtex              # mic Utam
  # 8: opsional an          
    # - pathofexile_x64.exe
    # - rocketleague.exe

# set this to true if you want the controls inverted (i.e. top is 0%, bottom is 100%)
invert_sliders: false

# settings for connecting to the arduino board
com_port: COM22
baud_rate: 9600

# adjust the amount of signal noise reduction depending on your hardware quality
# supported values are "low" (excellent hardware), "default" (regular hardware) or "high" (bad, noisy hardware)
noise_reduction: high
